WebMVC/ShopTestSE/ShopTestSE/Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTestSE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string CategoryID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> CurQuantity { get; set; }
        public string image { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

WebMVC/ShopTestSE/ShopTestSE/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopTestSE.Models;

namespace ShopTestSE.Controllers
{
    public class CategoryController : Controller
    {
        ShopConn db = new ShopConn();
        // GET: Category
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult CategoryPartial()
        {
            var categoryList = db.Categories.OrderBy(x => x.CategoryName).ToList();
            return PartialView(categoryList);
        }
    }
}

WebMVC/ShopTestSE/ShopTestSE/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopTestSE.Models;

namespace ShopTestSE.Controllers
{
    public class ProductsController : Controller
    {
        private ShopConn db = new ShopConn();

        // GET: Products
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category);
            return View(products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CateforyID", "CategoryName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductName,CategoryID,Price,CurQuantity,image")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CateforyID", "CategoryName", product.CategoryID);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CateforyID", "CategoryName", product.CategoryID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ProductName,CategoryID,Price,CurQuantity,image")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CateforyID", "CategoryName", product.CategoryID);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public PartialViewResult ProductListPartial()
        {
            var productList = db.Products.OrderByDescending(x => x.ProductID).ToList();
            return PartialView(productList);
        }

        public ActionResult ChoosePaymentType()
        {
            PaymentType paymentType = new PaymentType();
            paymentType.PayCollection = db.PaymentTypes.ToList<PaymentType>();
            return PartialView(paymentType);
        }
    }
}

WebMVC/ShopTestSE/ShopTestSE/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopTestSE.Models;

namespace ShopTestSE.Controllers
{
    public class ShoppingCartController : Controller
    {
        private ShopConn db = new ShopConn();
        // GET: ShoppingCart
        private String strCart = "Cart";
        //private object lsCart;

        // GET: ShoppingCart
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OrderNow(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            if (Session[strCart] == null)
            {
                List<Cart> lsCart = new List<Cart>
                {
                    new Cart(db.Products.Find(id),1)
                };
                Session[strCart] = lsCart;
            }
            else
            {
                List<Cart> lsCart = (List<Cart>)Session[strCart];
                int check = isExistingCheck(id);
                if (check == -1)
                {
                    lsCart.Add(new Cart(db.Products.Find(id), 1));
                }
                else
                {
                    lsCart[check].Quantity++;
                    Session[strCart] = lsCart;
                }
                //lsCart.Add(new Cart(db.Products.Find(id), 1));
            }

            return View("Index");
        }

        private int isExistingCheck(string id)
        {
            List<Cart> lsCart = (List<Cart>)Session[strCart];
            for (int i = 0; i < lsCart.Count; i++)
            {
                if (lsCart[i].Product.ProductID == id)
                {
                    return i;
                }
            }
            return -1;
        }

        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            int check = isExistingCheck(id);
            List<Cart> lsCart = (List<Cart>)Session[strCart];
            lsCart.RemoveAt(check);
            return View("Index");
        }

        public ActionResult UpdateCart(FormCollection frc)
        {
            string[] quantity = frc.GetValues("quantity");
            List<Cart> lstCart = (List<Cart>)Session[strCart];
            for (int i = 0; i < lstCart.Count; i++)
            {
                lstCart[i].Quantity = Convert.ToInt32(quantity[i]);
            }
            Session[strCart] = lstCart;
            return View("Index");
        }

        public ActionResult CheckOut()
        {

            return View("CheckOut");
        }

        public ActionResult ConfirmOder(FormCollection frc)
        {
            List<Cart> lstCart = (List<Cart>)Session[strCart];
            Agent agent = new Agent()
            {
                AgentName = frc["cusName"],
                AgentPhone = frc["cusPhone"],
                AgentAddress = frc["cusAddress"],
            };
            db.Agents.Add(agent);
            db.SaveChanges();
            PaymentType paymentType = new PaymentType();
            Order order = new Order()
            {
                AgentID = agent.AgentID,
                PaymentTypeID = paymentType.PaymentTypeID,
                OrderDate = DateTime.Now
            };
            db.Orders.Add(order);
            db.SaveChanges();
            foreach (Cart cart in lstCart)
            {
                OrderDetail orderDetail = new OrderDetail()
                {
                    OrderID = order.OrderID,
                    ProductID = cart.Product.ProductID,
                    Quantity = cart.Quantity,
                    Price = cart.Product.Price,
                    Status = "Processing"
                };
                db.OrderDetails.Add(orderDetail);
                db.SaveChanges();
            }
            Session.Remove(strCart);
            return View("OrderSuccess");
        }
    }
}

WebMVC/ShopTestSE/ShopTestSE/Views/Products/ChoosePaymentType.cshtml
@model ShopTestSE.Models.PaymentType
@Html.DropDownListFor(model => model.PaymentTypeID, new SelectList(Model.PayCollection, 
    "PaymentTypeID", "Type", "--Select--"))

WebMVC/ShopTestSE/ShopTestSE/Views/Products/Create.cshtml
@model ShopTestSE.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>;l

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebMVC/ShopTestSE/ShopTestSE/Views/Products/Delete.cshtml
@model ShopTestSE.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebMVC/ShopTestSE/ShopTestSE/Views/Products/Details.cshtml
@model ShopTestSE.Models.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProductID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebMVC/ShopTestSE/ShopTestSE/Views/Products/Edit.cshtml
@model ShopTestSE.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebMVC/ShopTestSE/ShopTestSE/Views/Products/Index.cshtml
@model IEnumerable<ShopTestSE.Models.Product>

@{
    ViewBag.Title = "Shop";
}

<link rel="stylesheet" type="text/css" href="~/Template/styles/bootstrap4/bootstrap.min.css">
<link href="~/Template/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="~/Template/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
<link rel="stylesheet" type="text/css" href="~/Template/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
<link rel="stylesheet" type="text/css" href="~/Template/plugins/OwlCarousel2-2.2.1/animate.css">
<link rel="stylesheet" type="text/css" href="~/Template/plugins/jquery-ui-1.12.1.custom/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="~/Template/styles/categories_styles.css">
<link rel="stylesheet" type="text/css" href="~/Template/styles/categories_responsive.css">

<h2>Index</h2>

<div class="sidebar">
    <div class="sidebar_section">
        <div class="sidebar_title">
            <h5>Product Category</h5>
        </div>
        <ul class="sidebar_categories">
            @Html.Action("CategoryPartial", "Category") 
        </ul>
    </div>
</div>

<div class="main_content">

    <!-- Products -->

    <div class="products_iso">
        <div class="row">
            <div class="col">

                <!-- Product Sorting -->

                <div class="product_sorting_container product_sorting_container_top">
                    <ul class="product_sorting">
                        <li>
                            <span class="type_sorting_text">Default Sorting</span>
                            <i class="fa fa-angle-down"></i>
                            <ul class="sorting_type">
                                <li class="type_sorting_btn" data-isotope-option='{ "sortBy": "original-order" }'><span>Default Sorting</span></li>
                                <li class="type_sorting_btn" data-isotope-option='{ "sortBy": "price" }'><span>Price</span></li>
                                <li class="type_sorting_btn" data-isotope-option='{ "sortBy": "name" }'><span>Product Name</span></li>
                            </ul>
                        </li>
                        <li>
                            <span>Show</span>
                            <span class="num_sorting_text">6</span>
                            <i class="fa fa-angle-down"></i>
                            <ul class="sorting_num">
                                <li class="num_sorting_btn"><span>6</span></li>
                                <li class="num_sorting_btn"><span>12</span></li>
                                <li class="num_sorting_btn"><span>24</span></li>
                            </ul>
                        </li>
                    </ul>
                    <div class="pages d-flex flex-row align-items-center">
                        <div class="page_current">
                            <span>1</span>
                            <ul class="page_selection">
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                            </ul>
                        </div>
                        <div class="page_total"><span>of</span> 3</div>
                        <div id="next_page" class="page_next"><a href="#"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></a></div>
                    </div>

                </div>


                @Html.Action("ProductListPartial", "Products")
                <!-- Product Grid -->
                @*@if (Model != null && Model.Any())
                {
                    foreach (var item in Model)
                    {
                        
                    }
                }*@





                <!-- Product Sorting -->

                <div class="product_sorting_container product_sorting_container_bottom clearfix">
                    <ul class="product_sorting">
                        <li>
                            <span>Show:</span>
                            <span class="num_sorting_text">04</span>
                            <i class="fa fa-angle-down"></i>
                            <ul class="sorting_num">
                                <li class="num_sorting_btn"><span>01</span></li>
                                <li class="num_sorting_btn"><span>02</span></li>
                                <li class="num_sorting_btn"><span>03</span></li>
                                <li class="num_sorting_btn"><span>04</span></li>
                            </ul>
                        </li>
                    </ul>
                    <span class="showing_results">Showing 1–3 of 12 results</span>
                    <div class="pages d-flex flex-row align-items-center">
                        <div class="page_current">
                            <span>1</span>
                            <ul class="page_selection">
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                            </ul>
                        </div>
                        <div class="page_total"><span>of</span> 3</div>
                        <div id="next_page_1" class="page_next"><a href="#"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></a></div>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>
			

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    @*<tr>*@
        @*<th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurQuantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </th>
        <th></th>*@
    @*</tr>*@

    @*@foreach (var item in Model)
    {
        <tr>*@
            @*<td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurQuantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.image)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.CategoryName)
            </td>*@
            @*<td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ProductID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ProductID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ProductID })
            </td>*@
        @*</tr>*@
    @*}*@

</table>

<script src="~/Template/js/jquery-3.2.1.min.js"></script>
<script src="~/Template/styles/bootstrap4/popper.js"></script>
<script src="~/Template/styles/bootstrap4/bootstrap.min.js"></script>
<script src="~/Template/plugins/Isotope/isotope.pkgd.min.js"></script>
<script src="~/Template/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
<script src="~/Template/plugins/easing/easing.js"></script>
<script src="~/Template/plugins/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
<script src="~/Template/js/categories_custom.js"></script>

WebMVC/ShopTestSE/ShopTestSE/Views/Products/ProductListPartial.cshtml
@using ShopTestSE.Models;
@model List<Product>

@{
    <div class="product-grid">
        @foreach (var item in Model)
        {

        <!-- Product 1 -->

        <div class="product-item men">
            <div class="product discount product_filter">
                <div class="product_image">
                    <img src='@Url.Content("~/Template/images_sup/"+item.image)'/>
                </div>
                <div class="favorite favorite_left"></div>
                @*<div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>Hot</span></div>*@
                <div class="product_info">
                    <h6 class="product_name"><a href="single.html">@item.ProductName</a></h6>
                    <div class="product_price">@item.Price VND</div>
                </div>
            </div>

            <div class="red_button add_to_cart_button"><a href="@Url.Action("OrderNow", "ShoppingCart", new { id = item.ProductID }, null)">add to cart</a></div>
        </div>
        }
    </div>
}